import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  learnSidebar: [
    {
      type: 'category',
      label: '📖 All About Core',
      link: {type: 'doc', id: 'intro'},
      items:[
          {
            type: 'category',
            collapsed: true,
            label: 'Introduction',
            items: ['Learn/introduction/what-is-core-chain',
                    'Learn/introduction/why-core-chain',
                    //'Learn/introduction/quickstart',
                    {
                      type: 'link',
                      label: 'Whitepaper', 
                      href: 'https://whitepaper.coredao.org/', 
                    },
                  ]
          },
          {
            type: 'category',
            collapsed: true,
            label: 'Core Concepts',
            link: {
              type: 'generated-index',
              title: 'Core Concepts',
              description: 'Learn about the Nuts and Bolts of the Core Ecosystem.',
              slug: '/category/core-concepts',
            },
            items: ['Learn/core-concepts/overview', 'Learn/core-concepts/architecture',
                      {
                        type: 'category',
                        collapsed: true,
                        label: 'Satoshi Plus Consensus',
                        items: [
                          'Learn/core-concepts/satoshi-plus-consensus/components',
                          'Learn/core-concepts/satoshi-plus-consensus/DPoW',
                          'Learn/core-concepts/satoshi-plus-consensus/DPoS',
                          'Learn/core-concepts/satoshi-plus-consensus/BitcoinStaking',
                          'Learn/core-concepts/satoshi-plus-consensus/validator-election',
                          'Learn/core-concepts/satoshi-plus-consensus/rewards', 
                          'Learn/core-concepts/satoshi-plus-consensus/security',
                          ]
                      },
                  ]
          },
          {
            type: 'category',
              collapsed: true,
              label: 'Products',
              link: {
                type: 'generated-index',
                title: 'Exploring Core: Pioneering DeFi Solutions for Bitcoin',
                description: 'Learn about the different innovative products offered by Core that are helping in unlocking the BTCfi landscape!',
                slug: '/category/products',
              },
              items: [
                {
                  type: 'category',
                    collapsed: true,
                    label: 'stCORE',
                    items: [
                      'Learn/products/stCore/overview',
                      'Learn/products/stCore/design',
                      {
                        type: 'category',
                          collapsed: true,
                          label: 'How To Guides',
                          items: [
                            'Learn/products/stCore/stCore-on-Core',
                          ]
                      },
                      
                    ]
                },
                {
                  type: 'category',
                    collapsed: true,
                    label: 'lstBTC',
                    items: [
                      'Learn/products/lstBTC/overview',
                    ]
                },
                {
                  type: 'category',
                    collapsed: true,
                    label: 'coreBTC (Sunsetted)',
                    items: [
                      'Learn/products/coreBTC/overview',
                      'Learn/products/coreBTC/design',
                      'Learn/products/coreBTC/how-to-guides',
                    ]
                },
              ]
          },
          {
            type: 'category',
              collapsed: true,
              label: 'Economics',
              items: [
                  'Learn/economics/core-token/tokenomics-and-utility',
              ]
          },
          'Learn/governance',
          
            {
              type: 'category',
              collapsed: true,
              label: 'Core Ignition',
              items: [
                  'CoreIgnition/Overview',
                  'CoreIgnition/Mechanics',
              ]
          },
          {
            type: 'category',
            collapsed: true,
            label: 'Security',
            items: [
                'Learn/audit',
                'Learn/bug-reporting',
            ]
          },
    ]
    },
  ],
  devGuideSidebar: [
    {
      type: "category",
      collapsed: true,
      label: "💻 Core for Developers",
      items: [
        "Dev-Guide/dev-tools", 
        "Dev-Guide/network-config",
        // {
        //   type: "category",
        //   collapsed: true,
        //   label: "Connecting to Core",
        //   items: ["Dev-Guide/dev-tools", "Dev-Guide/network-config"],
        // },
        {
          type: "category",
          collapsed: true,
          label: "RPC Endpoints",
          link: {
            type: "generated-index",
            title: "Core RPC Endpoints",
            description:
              "Core RPC Endpoints: Key Tools for Blockchain Development and Interaction",
            slug: "/category/rpc-list",
          },
          items: [
            "Dev-Guide/rpc-list",
            "Dev-Guide/rpc-cli",
            "Dev-Guide/rpc-postman",
          ],
        },
        {
          type: "category",
          collapsed: true,
          label: "Wallet Configurations",
          items: [
            "Dev-Guide/core-wallet-config",
            {
              type: "link",
              label: "Configure Custom Tokens",
              href: "https://support.metamask.io/manage-crypto/tokens/how-to-display-tokens-in-metamask/",
            },
            {
              type: "link",
              label: "Import Accounts",
              href: "https://support.metamask.io/start/how-to-import-an-account/",
            },
          ],
        },
        {
          type: "category",
          collapsed: true,
          label: "Dev Tools",
          items: ["Dev-Guide/core-faucet", "Dev-Guide/core-explorer"],
        },
        "Dev-Guide/precompile-addresses",

        {
          type: "category",
          collapsed: true,
          label: "Developer Guides",
          link: {
            type: "generated-index",
            title: "Developer Guides: Mastering Core Essentials",
            description:
              "Unlock Your Potential: Detailed Developer Guides to Build on Core",
            slug: "/category/dev-guides",
          },
          items: [
            "Dev-Guide/smart-contract-guidelines",
            "Dev-Guide/remix",
            "Dev-Guide/hardhat",
            "Dev-Guide/foundry",
            "Dev-Guide/contract-verify",
            {
              type: "link",
              label: "Build dapp on Core",
              href: "https://github.com/coredao-org/dapp-tutorial",
            },
          ],
        },
        {
          type: "category",
          collapsed: true,
          label: "Deploying Tokens on Core",
          items: ["Dev-Guide/erc20-tokens", "Dev-Guide/erc721-tokens"],
        },
        {
          type: "link",
          label: "Switchboard VRF",
          href: "https://docs.switchboard.xyz/product-documentation/randomness/tutorials/evm",
        },
        "Dev-Guide/core-subgraph",
        {
          type: "category",
          collapsed: true,
          label: "Bridging with Core",
          items: [
            "Dev-Guide/bridge-with-layerzero",
            "Dev-Guide/core-bridge-resources",
          ],
        },
      ],
    },
  ],

  faqSidebar: [
    {
      type: 'category',
      collapsed: true,
      label: '🤔 FAQs',
      items: ['FAQs/core-faqs', 'FAQs/core-node-faqs',
              'FAQs/validator-faqs', 'FAQs/delegator-faqs', 
              'FAQs/coreBTC-faqs', 'FAQs/btc-staking-faqs', 
              'FAQs/dual-staking-faqs',
              'FAQs/LST-stCore-faqs','FAQs/core-api-faqs', 
              'CoreIgnition/FAQs']
    },
  ],

  nodeSidebar:[ 
    {
      type: 'category',
      collapsed: true,
      label: '🔮 Running Core Nodes',
      items: ['Node/overview',    
      {
        type: 'category',
        collapsed: true,
        label: 'Node Configurations',
        items: ['Node/config/full-node', 'Node/config/rpc-node-config',
                'Node/config/archive-node-config', 'Node/config/snapshot-node-config',
                'Node/config/validator-node-config', ]
      },     
      'Node/sync/snapshot-sync',

      {
        type: 'category',
        collapsed: true,
        label: 'Become a Validator',
        items: ['Node/validator/overview',
        'Node/validator/running-validator',        
        'Node/validator/validator-register', 
        'Node/validator/validator-election',
        'Node/validator/rewards',
        {
          type: 'category',
          collapsed: true,
          label: 'Slashing',
          items: ['Node/slashing/overview', 'Node/slashing/slashing-fee'
        ]
        },
      ],
      },
      {
        type: 'category',
        collapsed: true,
        label: 'Node Maintenance',
        items: ['Node/maintenance/maintenance','Node/maintenance/network-upgrade', ]
      },
    ]
    },
  ],
  
  stakeDelegateSidebar:[
    {
      type: 'category',
      collapsed: true,
      label: '💸 Staking',
      items: ['stake-and-delegate/staking-overview',
        {
          type: 'category',
            collapsed: true,
            label: 'Non-Custodial BTC Staking',
            items: [
              'Learn/products/btc-staking/overview',
              'Learn/products/btc-staking/btc-staking-working',
              //'stake-and-delegate/dual-staking', 
              'Learn/products/btc-staking/design', 
              {
                type: 'category',
                  collapsed: true,
                  label: 'How To Guides',
                  items: [
                    'Learn/products/btc-staking/stake-btc-guide',
                    // 'Learn/products/btc-staking/dual-staking-guide',
                    'Learn/products/btc-staking/Redeeming-Guide',
                  ]
              },
            ]
        },    
        {
          type: 'category',
            collapsed: true,
            label: 'Dual Staking',
            items: [
              'stake-and-delegate/dual-staking', 
              'stake-and-delegate/dual-staking-working', 
              {
                type: 'category',
                  collapsed: true,
                  label: 'How To Guides',
                  items: [
                    'Learn/products/btc-staking/dual-staking-guide',
                  ]
              },
            ]
        },
       
      ]
    },
    {
      type: 'category',
      collapsed: true,
      label: '💰 Become a Delegator',
      items: ['stake-and-delegate/delegators', 'stake-and-delegate/delegating-core',
      'stake-and-delegate/delegating-hash']
    },
  ],

 apiSidebar:[
    {
      type: 'category',
      collapsed: true,
      label: 'Core Scan API',
      //link: {type: 'doc', id: 'api/api'},
      link: {
        type: 'generated-index',
        title: 'Core Scan API Endpoints',
        description: 'Explore the various Core Scan API endpoints for Core Mainnet and Testnet2',
        slug: '/api/core-api',
      },
      items: [
        {
          type: 'category',
          collapsed: true,
          label: '📚 Getting Started',
          link: {
            type: 'generated-index',
            title: 'Core Scan Tutorials',
            description: 'Learn about how to use the Core Scan API Endpoints',
            slug: '/api/core-api-tutorials',
          },
          items: [
            'api/tutorials/creating-an-account',
            'api/tutorials/generate-an-api-key',
            'api/tutorials/common-error-messages',
          ]
        },
        {
          type: 'category',
          collapsed: true,
          label: '📑 API Endpoints',
          link: {
            type: 'generated-index',
            title: 'Core Scan API Documentation',
            description: 'Explore the various Core Scan API Endpoints for Core Mainnet and Testnet2',
            slug: '/api/core-api-docs',
          },
          items: [
            {
              type: 'category',
              collapsed: true,
              label: '📑 Mainnet Endpoints',
              link: {
                type: 'generated-index',
                title: 'Core Scan API Documentation',
                description: 'Explore the various Core Scan API Endpoints for Core Mainnet',
                slug: '/api/core-api-mainnet-docs',
              },
              items: [ 
                require("./docs/api/mainnet/sidebar.ts"),
              ]
            },
            {
              type: 'category',
              collapsed: true,
              label: '📑 Testnet Endpoints',
              link: {
                type: 'generated-index',
                title: 'Core Scan API Documentation',
                description: 'Explore the various Core Scan API Endpoints for Core Testnet2',
                slug: '/api/core-api-testnet-docs',
              },
              items: [ 
                require("./docs/api/testnet/sidebar.ts")
              ]
            }, 
          ]
        },
      ]
    },
    
    {
      type: 'category',
      collapsed: true,
      label: 'Staking API',
      link: {
        type: 'generated-index',
        title: 'Staking API Documentation',
        description: 'Explore the various Staking API endpoint for Core Mainnet and Testnet2',
        slug: '/api/staking-api-docs',
      },
      items: [
        {
          type: 'category',
          collapsed: true,
          label: '📑 Mainnet API Endpoints',
          link: {
            type: 'generated-index',
            title: 'Staking API Documentation',
            description: 'Explore the various Staking API Endpoints for Core Mainnet',
            slug: '/api/mainnet-staking-api-docs',
          },
          items: [ 
            require("./docs/stakingAPI/mainnet/sidebar.ts"),
          ]
        },
        {
          type: 'category',
          collapsed: true,
          label: '📑 Testnet API Endpoints',
          link: {
            type: 'generated-index',
            title: 'Staking API Documentation',
            description: 'Explore the various Staking API Endpoints for Core Testnet2',
            slug: '/api/testnet-staking-api-docs',
          },
          items: [ 
            require("./docs/stakingAPI/testnet/sidebar.ts")
          ]
        }, 
      ]
    },
  ],

};

export default sidebars;
